version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps)"
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps)"
    groups:
      npm-minor-and-patch:
        update-types: [minor, patch]

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps)"
    groups:
      cargo-minor-and-patch:
        update-types: [minor, patch]
