[package]
name = "sweep-fs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
camino.workspace = true
crossbeam-deque.workspace = true
rayon.workspace = true
sweep-types = { path = "../sweep-types" }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
