[package]
name = "sweep-fs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
camino.workspace = true
crossbeam-deque.workspace = true
rayon.workspace = true
sweep-types = { path = "../sweep-types" }

[target.'cfg(target_os = "linux")'.dependencies]
rustix = { version = "1.1.4", features = ["fs"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Storage_FileSystem"] }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
